<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks to avoid order issues
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        // Truncate tables to ensure clean data
        $tables = [
            'permissions', 'role_permissions', 'user_permissions',
            'skeleton_modules', 'skeleton_sections', 'skeleton_items', 'skeleton_tokens',
            'categories', 'options', 'credentials', 'secure_keys', 'encrypted_tables',
            'encryption_progress', 'encryption_logs',
            'businesses', 'companies', 'roles', 'users', 'user_profiles'
        ];
        foreach ($tables as $table) {
            DB::table($table)->truncate();
        }

        // Skeleton Modules
        $modules = [
            [
                'id' => 1,
                'module_id' => 'MOD001',
                'name' => 'Dashboard',
                'system' => 'central',
                'icon' => 'ti ti-dashboard',
                'order' => 1,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'module_id' => 'MOD002',
                'name' => 'Profile',
                'system' => 'central',
                'icon' => 'ti ti-user',
                'order' => 2,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'module_id' => 'MOD003',
                'name' => 'Settings',
                'system' => 'central',
                'icon' => 'ti ti-settings',
                'order' => 3,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('skeleton_modules')->insert($modules);

        // Skeleton Sections
        $sections = [
            [
                'id' => 1,
                'section_id' => 'SEC001',
                'module_id' => 'MOD001',
                'name' => 'Home',
                'icon' => 'ti ti-home',
                'order' => 1,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'section_id' => 'SEC002',
                'module_id' => 'MOD001',
                'name' => 'Analytics',
                'icon' => 'ti ti-chart-bar',
                'order' => 2,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'section_id' => 'SEC003',
                'module_id' => 'MOD002',
                'name' => 'My Profile',
                'icon' => 'ti ti-user-circle',
                'order' => 1,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'section_id' => 'SEC004',
                'module_id' => 'MOD002',
                'name' => 'Security',
                'icon' => 'ti ti-shield',
                'order' => 2,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'section_id' => 'SEC005',
                'module_id' => 'MOD003',
                'name' => 'General',
                'icon' => 'ti ti-adjustments',
                'order' => 1,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'section_id' => 'SEC006',
                'module_id' => 'MOD003',
                'name' => 'Theme',
                'icon' => 'ti ti-palette',
                'order' => 2,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('skeleton_sections')->insert($sections);

        // Skeleton Items
        $items = [
            [
                'id' => 1,
                'item_id' => 'ITM001',
                'section_id' => 'SEC003',
                'name' => 'Edit Info',
                'icon' => 'ti ti-edit',
                'order' => 1,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'item_id' => 'ITM002',
                'section_id' => 'SEC003',
                'name' => 'Change Password',
                'icon' => 'ti ti-lock',
                'order' => 2,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'item_id' => 'ITM003',
                'section_id' => 'SEC005',
                'name' => 'App',
                'icon' => 'ti ti-apps',
                'order' => 1,
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('skeleton_items')->insert($items);

        // Permissions
        $permissionTypes = ['create', 'view', 'edit', 'delete', 'import', 'export'];
        $permissions = [];
        $permissionId = 1;

        // Module Permissions
        foreach ($modules as $module) {
            foreach ($permissionTypes as $type) {
                $permissions[] = [
                    'id' => $permissionId++,
                    'type' => $type,
                    'name' => $module['name'],
                    'created_by' => 'system',
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        // Section Permissions
        foreach ($sections as $section) {
            $module = collect($modules)->firstWhere('module_id', $section['module_id']);
            foreach ($permissionTypes as $type) {
                $permissions[] = [
                    'id' => $permissionId++,
                    'type' => $type,
                    'name' => $module['name'] . '::' . $section['name'],
                    'created_by' => 'system',
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        // Item Permissions
        foreach ($items as $item) {
            $section = collect($sections)->firstWhere('section_id', $item['section_id']);
            $module = collect($modules)->firstWhere('module_id', $section['module_id']);
            foreach ($permissionTypes as $type) {
                $permissions[] = [
                    'id' => $permissionId++,
                    'type' => $type,
                    'name' => $module['name'] . '::' . $section['name'] . '::' . $item['name'],
                    'created_by' => 'system',
                    'updated_by' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        DB::table('permissions')->insert($permissions);

        // Role Permissions
        $rolePermissions = [];
        $rolePermissionId = 1;

        // Supreme (role_id=1): All permissions
        foreach ($permissions as $permission) {
            $rolePermissions[] = [
                'id' => $rolePermissionId++,
                'role_id' => 1,
                'permission_id' => $permission['id'],
                'created_by' => 'system',
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        // Support (role_id=2): View and export permissions
        $supportPermissions = collect($permissions)->filter(function ($perm) {
            return in_array($perm['type'], ['view', 'export']);
        })->pluck('id')->toArray();
        foreach ($supportPermissions as $permId) {
            $rolePermissions[] = [
                'id' => $rolePermissionId++,
                'role_id' => 2,
                'permission_id' => $permId,
                'created_by' => 'system',
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        // Developer (role_id=3): Create, edit, view permissions
        $developerPermissions = collect($permissions)->filter(function ($perm) {
            return in_array($perm['type'], ['create', 'edit', 'view']);
        })->pluck('id')->toArray();
        foreach ($developerPermissions as $permId) {
            $rolePermissions[] = [
                'id' => $rolePermissionId++,
                'role_id' => 3,
                'permission_id' => $permId,
                'created_by' => 'system',
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        // Guest (role_id=4): View permissions only
        $guestPermissions = collect($permissions)->filter(function ($perm) {
            return $perm['type'] === 'view';
        })->pluck('id')->toArray();
        foreach ($guestPermissions as $permId) {
            $rolePermissions[] = [
                'id' => $rolePermissionId++,
                'role_id' => 4,
                'permission_id' => $permId,
                'created_by' => 'system',
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('role_permissions')->insert($rolePermissions);

        // Businesses
        $businesses = [
            [
                'id' => 1,
                'business_id' => 'CENTRAL',
                'name' => 'Gotit Biometric HR',
                'legal_name' => 'Gotit Biometric HR Pvt Ltd',
                'logo' => null,
                'industry' => 'HR Tech',
                'registration_no' => 'REG001',
                'email' => 'info@got4all.com',
                'phone' => '+91-9000000000',
                'website' => 'https://got4all.com',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'address_json' => '{}',
                'no_of_employees' => 100,
                'hr_contact_email' => 'hr@got4all.com',
                'hr_contact_phone' => '+91-9000000001',
                'business_size' => 'small',
                'currency' => 'INR',
                'language' => 'English',
                'founded_date' => '2018-01-01',
                'tax_id' => 'TAXC001',
                'license_key' => Str::uuid(),
                'subscription_plan' => 'basic',
                'billing_status' => 'active',
                'database_name' => 'central_db',
                'total_migrations' => 0,
                'total_migrated' => 0,
                'migrated_at' => null,
                'database_status' => 'active',
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'business_id' => 'BIZ0001',
                'name' => 'Tata Technologies',
                'legal_name' => 'Tata Technologies Ltd',
                'logo' => null,
                'industry' => 'Technology',
                'registration_no' => 'REG002',
                'email' => 'contact@tatatech.in',
                'phone' => '+91-9876000001',
                'website' => 'https://tatatech.in',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'address_json' => '{}',
                'no_of_employees' => 15000,
                'hr_contact_email' => 'hr@tatatech.in',
                'hr_contact_phone' => '+91-9876000002',
                'business_size' => 'large',
                'currency' => 'INR',
                'language' => 'English',
                'founded_date' => '1899-01-01',
                'tax_id' => 'TAXIN001',
                'license_key' => Str::uuid(),
                'subscription_plan' => 'basic',
                'billing_status' => 'active',
                'database_name' => 'tatadb',
                'total_migrations' => 0,
                'total_migrated' => 0,
                'migrated_at' => null,
                'database_status' => 'active',
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'business_id' => 'BIZ0002',
                'name' => 'Infosys Solutions',
                'legal_name' => 'Infosys Solutions Pvt Ltd',
                'logo' => null,
                'industry' => 'IT Services',
                'registration_no' => 'REG003',
                'email' => 'contact@infosys.in',
                'phone' => '+91-9123000001',
                'website' => 'https://infosys.in',
                'country' => 'India',
                'timezone' => 'Asia/Kolkata',
                'address_json' => '{}',
                'no_of_employees' => 18000,
                'hr_contact_email' => 'hr@infosys.in',
                'hr_contact_phone' => '+91-9123000002',
                'business_size' => 'large',
                'currency' => 'INR',
                'language' => 'English',
                'founded_date' => '1981-07-02',
                'tax_id' => 'TAXIN002',
                'license_key' => Str::uuid(),
                'subscription_plan' => 'basic',
                'billing_status' => 'active',
                'database_name' => 'infosysdb',
                'total_migrations' => 0,
                'total_migrated' => 0,
                'migrated_at' => null,
                'database_status' => 'active',
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('businesses')->insert($businesses);

        // Companies
        $companies = [
            // BIZ0001 (Tata Technologies)
            [
                'id' => 1,
                'company_id' => 'CMP0001',
                'business_id' => 'BIZ0001',
                'name' => 'Tata Motors',
                'legal_name' => 'Tata Motors Ltd',
                'industry' => 'Automobile',
                'industry_subtype' => 'Manufacturing',
                'registration_no' => 'REG004',
                'email' => 'motors@tata.in',
                'phone' => '+91-9876100001',
                'address_json' => '{}',
                'operating_hours_json' => '{}',
                'employee_count' => 3000,
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'company_id' => 'CMP0002',
                'business_id' => 'BIZ0001',
                'name' => 'TCS',
                'legal_name' => 'Tata Consultancy Services Pvt Ltd',
                'industry' => 'IT',
                'industry_subtype' => 'Software Services',
                'registration_no' => 'REG005',
                'email' => 'tcs@tata.in',
                'phone' => '+91-9876200002',
                'address_json' => '{}',
                'operating_hours_json' => '{}',
                'employee_count' => 8000,
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'company_id' => 'CMP0003',
                'business_id' => 'BIZ0001',
                'name' => 'Tata Steel',
                'legal_name' => 'Tata Steel Ltd',
                'industry' => 'Steel',
                'industry_subtype' => 'Metallurgy',
                'registration_no' => 'REG006',
                'email' => 'steel@tata.in',
                'phone' => '+91-9876300003',
                'address_json' => '{}',
                'operating_hours_json' => '{}',
                'employee_count' => 5000,
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // BIZ0002 (Infosys Solutions)
            [
                'id' => 4,
                'company_id' => 'CMP0001',
                'business_id' => 'BIZ0002',
                'name' => 'Infosys Bangalore',
                'legal_name' => 'Infosys Bangalore Ltd',
                'industry' => 'IT Services',
                'industry_subtype' => 'Software Development',
                'registration_no' => 'REG007',
                'email' => 'blr@infosys.in',
                'phone' => '+91-9123000001',
                'address_json' => '{}',
                'operating_hours_json' => '{}',
                'employee_count' => 6000,
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'company_id' => 'CMP0002',
                'business_id' => 'BIZ0002',
                'name' => 'Infosys Pune',
                'legal_name' => 'Infosys Pune Ltd',
                'industry' => 'IT Services',
                'industry_subtype' => 'Consulting',
                'registration_no' => 'REG008',
                'email' => 'pune@infosys.in',
                'phone' => '+91-9123000002',
                'address_json' => '{}',
                'operating_hours_json' => '{}',
                'employee_count' => 4000,
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'company_id' => 'CMP0003',
                'business_id' => 'BIZ0002',
                'name' => 'Infosys Hyderabad',
                'legal_name' => 'Infosys Hyderabad Ltd',
                'industry' => 'IT Services',
                'industry_subtype' => 'Cloud Services',
                'registration_no' => 'REG009',
                'email' => 'hyd@infosys.in',
                'phone' => '+91-9123000003',
                'address_json' => '{}',
                'operating_hours_json' => '{}',
                'employee_count' => 5000,
                'meta_data' => '{}',
                'status' => 'active',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('companies')->insert($companies);

        // Roles
        $roles = [
            [
                'id' => 1,
                'name' => 'Supreme',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Support',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Developer',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Guest',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('roles')->insert($roles);

        // Users
        $users = [
            // Global Users (business_id = CENTRAL)
            [
                'id' => 1,
                'user_id' => 'USR0001',
                'business_id' => 'CENTRAL',
                'first_name' => 'Supreme',
                'last_name' => 'Admin',
                'email' => 'supreme@system.in',
                'username' => 'supreme.admin',
                'password' => '$2y$12$eXlUhkp.JLmNR8Z242VReuomhtlVmN57W1LVDhYxUuVGv9obfq40G',
                'role_id' => 1,
                'provider' => null,
                'provider_id' => null,
                'provider_token' => null,
                'provider_refresh_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'two_factor_method' => null,
                'device_token' => null,
                'device_type' => null,
                'fcm_enabled' => 0,
                'password_updated_at' => now(),
                'max_logins' => 5,
                'verification' => 'verified',
                'account_status' => 'active',
                'profile' => '{}',
                'last_login_at' => null,
                'remember_token' => null,
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'user_id' => 'USR0002',
                'business_id' => 'CENTRAL',
                'first_name' => 'Support',
                'last_name' => 'Team',
                'email' => 'support@system.in',
                'username' => 'support.team',
                'password' => '$2y$12$eXlUhkp.JLmNR8Z242VReuomhtlVmN57W1LVDhYxUuVGv9obfq40G',
                'role_id' => 2,
                'provider' => null,
                'provider_id' => null,
                'provider_token' => null,
                'provider_refresh_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'two_factor_method' => null,
                'device_token' => null,
                'device_type' => null,
                'fcm_enabled' => 0,
                'password_updated_at' => now(),
                'max_logins' => 5,
                'verification' => 'verified',
                'account_status' => 'active',
                'profile' => '{}',
                'last_login_at' => null,
                'remember_token' => null,
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'user_id' => 'USR0003',
                'business_id' => 'CENTRAL',
                'first_name' => 'Developer',
                'last_name' => 'Core',
                'email' => 'developer@system.in',
                'username' => 'developer.core',
                'password' => '$2y$12$eXlUhkp.JLmNR8Z242VReuomhtlVmN57W1LVDhYxUuVGv9obfq40G',
                'role_id' => 3,
                'provider' => null,
                'provider_id' => null,
                'provider_token' => null,
                'provider_refresh_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'two_factor_method' => null,
                'device_token' => null,
                'device_type' => null,
                'fcm_enabled' => 0,
                'password_updated_at' => now(),
                'max_logins' => 5,
                'verification' => 'verified',
                'account_status' => 'active',
                'profile' => '{}',
                'last_login_at' => null,
                'remember_token' => null,
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'user_id' => 'USR0004',
                'business_id' => 'CENTRAL',
                'first_name' => 'Guest',
                'last_name' => 'User',
                'email' => 'guest@system.in',
                'username' => 'guest.user',
                'password' => '$2y$12$eXlUhkp.JLmNR8Z242VReuomhtlVmN57W1LVDhYxUuVGv9obfq40G',
                'role_id' => 4,
                'provider' => null,
                'provider_id' => null,
                'provider_token' => null,
                'provider_refresh_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'two_factor_method' => null,
                'device_token' => null,
                'device_type' => null,
                'fcm_enabled' => 0,
                'password_updated_at' => now(),
                'max_logins' => 1,
                'verification' => 'unverified',
                'account_status' => 'active',
                'profile' => '{}',
                'last_login_at' => null,
                'remember_token' => null,
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Business-Specific Users
            [
                'id' => 5,
                'user_id' => 'USR0005',
                'business_id' => 'BIZ0001',
                'first_name' => 'Vikram',
                'last_name' => 'Singh',
                'email' => 'vikram.singh@tatatech.in',
                'username' => 'vikram.singh',
                'password' => '$2y$12$eXlUhkp.JLmNR8Z242VReuomhtlVmN57W1LVDhYxUuVGv9obfq40G',
                'role_id' => 1,
                'provider' => null,
                'provider_id' => null,
                'provider_token' => null,
                'provider_refresh_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'two_factor_method' => null,
                'device_token' => null,
                'device_type' => null,
                'fcm_enabled' => 0,
                'password_updated_at' => now(),
                'max_logins' => 5,
                'verification' => 'verified',
                'account_status' => 'active',
                'profile' => '{}',
                'last_login_at' => null,
                'remember_token' => null,
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'user_id' => 'USR0006',
                'business_id' => 'BIZ0002',
                'first_name' => 'Anjali',
                'last_name' => 'Patel',
                'email' => 'anjali.patel@infosys.in',
                'username' => 'anjali.patel',
                'password' => '$2y$12$eXlUhkp.JLmNR8Z242VReuomhtlVmN57W1LVDhYxUuVGv9obfq40G',
                'role_id' => 1,
                'provider' => null,
                'provider_id' => null,
                'provider_token' => null,
                'provider_refresh_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'two_factor_method' => null,
                'device_token' => null,
                'device_type' => null,
                'fcm_enabled' => 0,
                'password_updated_at' => now(),
                'max_logins' => 5,
                'verification' => 'verified',
                'account_status' => 'active',
                'profile' => '{}',
                'last_login_at' => null,
                'remember_token' => null,
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'user_id' => 'USR0007',
                'business_id' => 'BIZ0002',
                'first_name' => 'Rahul',
                'last_name' => 'Sharma',
                'email' => 'rahul.sharma@infosys.in',
                'username' => 'rahul.sharma',
                'password' => '$2y$12$eXlUhkp.JLmNR8Z242VReuomhtlVmN57W1LVDhYxUuVGv9obfq40G',
                'role_id' => 2,
                'provider' => null,
                'provider_id' => null,
                'provider_token' => null,
                'provider_refresh_token' => null,
                'two_factor_enabled' => 0,
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'two_factor_method' => null,
                'device_token' => null,
                'device_type' => null,
                'fcm_enabled' => 0,
                'password_updated_at' => now(),
                'max_logins' => 5,
                'verification' => 'verified',
                'account_status' => 'active',
                'profile' => '{}',
                'last_login_at' => null,
                'remember_token' => null,
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'delete_on' => null,
                'restored_at' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('users')->insert($users);

        // User Profiles
        $userProfiles = [
            [
                'id' => 1,
                'user_id' => 'USR0001',
                'phone' => '+91-9000000001',
                'date_of_birth' => '1980-01-01',
                'gender' => 'Male',
                'address' => null,
                'city' => null,
                'state' => null,
                'country' => 'India',
                'postal_code' => null,
                'timezone' => 'Asia/Kolkata',
                'meta_data' => '{}',
                'bio' => 'System Administrator',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'user_id' => 'USR0002',
                'phone' => '+91-9000000002',
                'date_of_birth' => '1980-01-01',
                'gender' => null,
                'address' => null,
                'city' => null,
                'state' => null,
                'country' => 'India',
                'postal_code' => null,
                'timezone' => 'Asia/Kolkata',
                'meta_data' => '{}',
                'bio' => 'Support Team Member',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'user_id' => 'USR0003',
                'phone' => '+91-9000000003',
                'date_of_birth' => '1980-01-01',
                'gender' => null,
                'address' => null,
                'city' => null,
                'state' => null,
                'country' => 'India',
                'postal_code' => null,
                'timezone' => 'Asia/Kolkata',
                'meta_data' => '{}',
                'bio' => 'Core Developer',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'user_id' => 'USR0004',
                'phone' => '+91-9000000004',
                'date_of_birth' => '1980-01-01',
                'gender' => null,
                'address' => null,
                'city' => null,
                'state' => null,
                'country' => 'India',
                'postal_code' => null,
                'timezone' => 'Asia/Kolkata',
                'meta_data' => '{}',
                'bio' => 'Guest User',
                'created_by' => 'USR0001',
                'updated_by' => 'USR0001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'user_id' => 'USR0005',
                'phone' => '+91-9876100007',
                'date_of_birth' => '1985-06-15',
                'gender' => 'Male',
                'address' => '123 MG Road',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'country' => 'India',
                'postal_code' => '411001',
                'timezone' => 'Asia/Kolkata',
                'meta_data' => '{}',
                'bio' => 'Senior Manager at Tata Technologies',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'user_id' => 'USR0006',
                'phone' => '+91-9123000013',
                'date_of_birth' => '1984-03-10',
                'gender' => 'Female',
                'address' => '456 Brigade Road',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'country' => 'India',
                'postal_code' => '560001',
                'timezone' => 'Asia/Kolkata',
                'meta_data' => '{}',
                'bio' => 'HR Lead at Infosys Solutions',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'user_id' => 'USR0007',
                'phone' => '+91-9123000014',
                'date_of_birth' => '1986-07-15',
                'gender' => 'Male',
                'address' => '789 Banjara Hills',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'country' => 'India',
                'postal_code' => '500034',
                'timezone' => 'Asia/Kolkata',
                'meta_data' => '{}',
                'bio' => 'Support Manager at Infosys Solutions',
                'created_by' => 'USR0005',
                'updated_by' => 'USR0005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('user_profiles')->insert($userProfiles);

        // Secure Keys
        $secureKeys = [
            [
                'business_id' => 'CENTRAL',
                'key' => Str::random(32),
                'version' => 'v1',
                'is_active' => true,
                'secure_version' => null,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('secure_keys')->insert($secureKeys);

        // Encrypted Tables
        $encryptedTables = [
            [
                'system' => 'business',
                'table' => 'users',
                'columns' => json_encode(['email', 'password']),
                'is_active' => true,
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('encrypted_tables')->insert($encryptedTables);

        // Encryption Progress
        $encryptionProgress = [
            [
                'business_id' => 'CENTRAL',
                'database_name' => 'central_db',
                'total_tables' => 10,
                'tables_encrypted' => 2,
                'status' => 'pending',
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('encryption_progress')->insert($encryptionProgress);

        // Encryption Logs
        $encryptionLogs = [
            [
                'business_id' => 'CENTRAL',
                'user_id' => 'USR0001',
                'table' => 'users',
                'old_version' => 'v1',
                'new_version' => 'v2',
                're_encrypted_at' => now(),
                'created_by' => 'system',
                'updated_by' => null,
                'deleted_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('encryption_logs')->insert($encryptionLogs);

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}